{{- if .Values.servingRuntime.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llama3-2-3b.fullname" . }}-chat-template
  labels:
    {{- include "llama3-2-3b.labels" . | nindent 4 }}
data:
  tool_chat_template_llama3.2_json.jinja: |
{{ .Files.Get "files/tool_chat_template_llama3.2_json.jinja" | nindent 4 }}
{{- end }}