apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llama3-2-3b
  labels:
    {{- include "llama3-2-3b.labels" . | nindent 4 }}
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/display-name: {{ .Values.inferenceService.displayName | default "llama3.2-3b" }}
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
    serving.kserve.io/deploymentMode: RawDeployment
  finalizers:
    - serving.kserve.io/inferenceservice-finalizer
spec:
  {{- $device := lower (.Values.device | default "gpu") }}
  {{- $resources := index .Values.resources $device }}
  {{- $tolerations := index .Values.tolerations $device }}
  predictor:
    maxReplicas: {{ .Values.inferenceService.maxReplicas | default 1 }}
    minReplicas: {{ .Values.inferenceService.minReplicas | default 1 }}
    model:
      modelFormat:
        name: {{ .Values.inferenceService.modelFormat | default "vLLM" }}
      name: {{ .Values.inferenceService.modelName | default "" }}
      resources:
        {{- toYaml $resources | nindent 8 }}
      runtime: llama3-2-3b
      storageUri: {{ .Values.inferenceService.storageUri | default "oci://quay.io/redhat-ai-services/modelcar-catalog:llama-3.2-3b-instruct" }}
    {{- if $tolerations }}
    tolerations:
      {{- toYaml $tolerations | nindent 6 }}
    {{- end }}